/*

Cyclical figurate numbers
Problem 61

Triangle, square, pentagonal, hexagonal, heptagonal, and octagonal numbers are
all figurate (polygonal) numbers and are generated by the following formulae:

Triangle        P3, n=n(n+1)/2       1, 3, 6, 10, 15, ...
Square          P4, n=n2             1, 4, 9, 16, 25, ...
Pentagonal      P5, n=n(3n−1)/2      1, 5, 12, 22, 35, ...
Hexagonal       P6, n=n(2n−1)        1, 6, 15, 28, 45, ...
Heptagonal      P7, n=n(5n−3)/2      1, 7, 18, 34, 55, ...
Octagonal       P8, n=n(3n−2)        1, 8, 21, 40, 65, ...

The ordered set of three 4-digit numbers: 8128, 2882, 8281, has three
interesting properties.

1. The set is cyclic, in that the last two digits of each number is the first
two digits of the next number (including the last number with the first).
2. Each polygonal type: triangle (P3,127=8128), square (P4,91=8281), and
pentagonal (P5,44=2882), is represented by a different number in the set.
3. This is the only set of 4-digit numbers with this property.

Find the sum of the only ordered set of six cyclic 4-digit numbers for which
each polygonal type: triangle, square, pentagonal, hexagonal, heptagonal, and
octagonal, is represented by a different number in the set.


Solution:

28684

*/


#include <stdio.h>

int numbers[6][100][3] = {0};
int count[6] = {0};

int makeNumber(int type, int n, int arr[]) {
    int number;
    type += 3;
    switch (type) {
        case 3:
            number = n * (n + 1) / 2;
            break;
        case 4:
            number = n * n;
            break;
        case 5:
            number = n * (3 * n - 1) / 2;
            break;
        case 6:
            number = n * (2 * n - 1);
            break;
        case 7:
            number = n * (5 * n - 3) / 2;
            break;
        case 8:
            number = n * (3 * n - 2);
            break;
    }

    // number
    arr[0] = number;
    // first two digits
    arr[1] = number / 100;
    // last two digits
    arr[2] = number % 100;
}

int check(int p[]) {
    int sum = 0;

    int pos0 = p[0];
    int pos1 = p[1];
    int pos2 = p[2];
    int pos3 = p[3];
    int pos4 = p[4];
    int pos5 = p[5];

    int counter0;
    int counter1;
    int counter2;
    int counter3;
    int counter4;
    int counter5;

    for (counter0 = 0; counter0 < count[pos0]; counter0++) {
        for (counter1 = 0; numbers[pos1][counter1][1] <= numbers[pos0][counter0][2]; counter1++) {
            if (numbers[pos0][counter0][2] != numbers[pos1][counter1][1]) {
                continue;
            }
            for (counter2 = 0; numbers[pos2][counter2][1] <= numbers[pos1][counter1][2]; counter2++) {
                if (numbers[pos1][counter1][2] != numbers[pos2][counter2][1]) {
                    continue;
                }
                for (counter3 = 0; numbers[pos3][counter3][1] <= numbers[pos2][counter2][2]; counter3++) {
                    if (numbers[pos2][counter2][2] != numbers[pos3][counter3][1]) {
                        continue;
                    }
                    for (counter4 = 0; numbers[pos4][counter4][1] <= numbers[pos3][counter3][2]; counter4++) {
                        if (numbers[pos3][counter3][2] != numbers[pos4][counter4][1]) {
                            continue;
                        }
                        for (counter5 = 0; numbers[pos5][counter5][1] <= numbers[pos4][counter4][2]; counter5++) {
                            if (numbers[pos4][counter4][2] != numbers[pos5][counter5][1]) {
                                continue;
                            }
                            if (numbers[pos5][counter5][2] != numbers[pos0][counter0][1]) {
                                continue;
                            }

                            sum += numbers[pos0][counter0][0];
                            sum += numbers[pos1][counter1][0];
                            sum += numbers[pos2][counter2][0];
                            sum += numbers[pos3][counter3][0];
                            sum += numbers[pos4][counter4][0];
                            sum += numbers[pos5][counter5][0];

                            printf("Sum: %d\n", sum);

                            return 1;
                        }
                    }
                }
            }
        }
    }

    return 0;
}

void swap(int *a, int *b) {
    int tmp;
    tmp = *a;
    *a = *b;
    *b = tmp;
}

// http://www.geeksforgeeks.org/write-a-c-program-to-print-all-permutations-of-a-given-string/
int perm(int a[], int l, int r) {
    int i, ret = 0;
    if (l == r) {
        if (check(a)) {
            return 1;
        }
    } else {
        for (i = l; i <= r; i++) {
            swap((a + l), (a + i));
            ret = perm(a, l + 1, r);
            if (ret == 1) {
                return ret;
            }
            swap((a + l), (a + i));
        }
    }

    return 0;
}

int main() {
    int i, j, k;
    int ret[3];
    int arr[] = {0, 1, 2, 3, 4, 5};

    for (i = 1; i < 150; i++) {
        for (j = 0; j < 6; j++) {
            makeNumber(j, i, ret);
            if (ret[0] > 1000 && ret[0] < 10000 && ret[0] % 100 >= 10) {
                for (k = 0; k < 3; k++) {
                    numbers[j][count[j]][k] = ret[k];
                }
                count[j]++;
            }
        }
    }

    perm(arr, 0, 5);

    return 0;
}