#!/usr/bin/env python
# -*- coding: utf-8 -*-
#

def main():
    """
    Even Fibonacci numbers
    Problem 2

    Each new term in the Fibonacci sequence is generated by adding the
    previous two terms. By starting with 1 and 2, the first 10 terms
    will be:

    1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

    By considering the terms in the Fibonacci sequence whose values do
    not exceed four million, find the sum of the even-valued terms.
    """
    evenSum = 0
    loop = 1
    prev = 0
    fib = 1
    
    while (fib <= 4000000):
        if (fib % 2 == 0):
            evenSum += fib
        tmp = prev
        prev = fib
        fib = fib + tmp
        
    print evenSum
    return 0

if __name__ == '__main__':
    main()

